version: '3.8'
services: 
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .prod.env
    ports:
      - 5000:5000
    command: pnpm run prod
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: